version: '3.8'

services:

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "5051:8080"

  postgres:
    image: postgres:15-alpine
    container_name: techtask
    environment:
      POSTGRES_USER: techtask
      POSTGRES_PASSWORD: techtask
      POSTGRES_DB: techtask
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
